export const PRODUCTOS = [
  { id: 'p1', codigo: 'CL001', nombre: 'Cilindro GLP 5 kg', descripcion: 'Cilindro de gas licuado de petróleo 5 kg. Para uso residencial (cocina, calefacción pequeña).', residencial: 6500, comercial: 6000, stock: 80, stockCritico: 5, categoria: 'Cilindros de Gas', imagen: '/IMAGENES/cilindro de 5 K.png' },
  { id: 'p2', codigo: 'CL002', nombre: 'Cilindro GLP 11 kg', descripcion: 'Cilindro estándar doméstico. El más utilizado en hogares chilenos.', residencial: 12000, comercial: 11000, stock: 200, stockCritico: 5, categoria: 'Cilindros de Gas', imagen: '/IMAGENES/cilindro de 11K.png' },
  { id: 'p3', codigo: 'CL003', nombre: 'Cilindro GLP 15 kg', descripcion: 'Cilindro de mayor capacidad para hogares de alto consumo o locales pequeños.', residencial: 16000, comercial: 14500, stock: 90, stockCritico: 5, categoria: 'Cilindros de Gas', imagen: '/IMAGENES/cilindro de 15K.png' },
  { id: 'p4', codigo: 'CL004', nombre: 'Cilindro GLP 45 kg', descripcion: 'Cilindro industrial. Uso comercial: restaurantes, talleres, locales.', residencial: 45000, comercial: 40000, stock: 30, stockCritico: 5, categoria: 'Cilindros de Gas', imagen: '/IMAGENES/cilindro de 45K.png' },
  { id: 'p5', codigo: 'RG001', nombre: 'Regulador doméstico estándar', descripcion: 'Regulador de 1 etapa para cilindros 5, 11 y 15 kg. Presión de salida 28 mbar.', residencial: 8990, comercial: 8200, stock: 45, stockCritico: 5, categoria: 'Reguladores', imagen: '/IMAGENES/Regulador Standar.png' },
  { id: 'p6', codigo: 'RG002', nombre: 'Regulador de alta presión', descripcion: 'Regulador para cocinas industriales o equipos de mayor consumo. Presión regulable.', residencial: 18990, comercial: 17000, stock: 12, stockCritico: 5, categoria: 'Reguladores', imagen: '/IMAGENES/Regaulador de Alta presion.png' },
  { id: 'p7', codigo: 'RG003', nombre: 'Regulador dual (2 salidas)', descripcion: 'Permite conectar dos artefactos simultáneamente al mismo cilindro.', residencial: 14990, comercial: 13500, stock: 18, stockCritico: 5, categoria: 'Reguladores', imagen: '/IMAGENES/Regulador Dual.png' },
  { id: 'p8', codigo: 'MG001', nombre: 'Manguera gas 1.5 m', descripcion: 'Manguera flexible homologada. Diámetro interior 9 mm.', residencial: 3990, comercial: 3500, stock: 80, stockCritico: 5, categoria: 'Mangueras y Conexiones', imagen: '/IMAGENES/Manguera gas 1.5 m.png' },
  { id: 'p9', codigo: 'MG002', nombre: 'Manguera gas 3 m', descripcion: 'Manguera larga para instalaciones donde el artefacto está alejado del cilindro.', residencial: 6990, comercial: 6200, stock: 50, stockCritico: 5, categoria: 'Mangueras y Conexiones', imagen: '/IMAGENES/Manguera gas 3 m.png' },
  { id: 'p10', codigo: 'MG003', nombre: 'Abrazadera metálica', descripcion: 'Abrazadera de acero para asegurar la conexión manguera-regulador.', residencial: 990, comercial: 800, stock: 200, stockCritico: 5, categoria: 'Mangueras y Conexiones', imagen: '/IMAGENES/Abrazadera metálica.png' },
  { id: 'p11', codigo: 'MG004', nombre: 'Kit conexión completo', descripcion: 'Todo lo necesario para instalar un cilindro nuevo.', residencial: 12990, comercial: 11500, stock: 25, stockCritico: 5, categoria: 'Mangueras y Conexiones', imagen: '/IMAGENES/kit completo.png' },
  { id: 'p12', codigo: 'AC001', nombre: 'Carro porta cilindro 11/15 kg', descripcion: 'Carro metálico con ruedas para transportar cilindros con seguridad.', residencial: 12990, comercial: 11000, stock: 20, stockCritico: 5, categoria: 'Accesorios', imagen: '/IMAGENES/carro transportador de gas.png' },
  { id: 'p13', codigo: 'AC002', nombre: 'Tapa protectora para válvula', descripcion: 'Tapa de plástico ABS para proteger la válvula durante el transporte.', residencial: 1490, comercial: 1200, stock: 60, stockCritico: 5, categoria: 'Accesorios', imagen: '/IMAGENES/Tapa de plástico ABS.png' },
  { id: 'p14', codigo: 'AC003', nombre: 'Detector de gas a batería', descripcion: 'Sensor electroquímico. Alarma sonora y visual ante fuga de gas GLP.', residencial: 19990, comercial: 17000, stock: 8, stockCritico: 5, categoria: 'Accesorios', imagen: '/IMAGENES/Sensor electroquímico.png' }
]